name: Generate Icons JSON

on:
  push:
    paths:
      - icons/**  # 监听 icons 文件夹的更改

jobs:
  generate-json:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Generate JSON file
      run: |
        python <<EOF
        import os, json
        folder_path = "icons"
        base_url = "https://raw.githubusercontent.com/${{ github.repository }}/main/icons/"
        data = {"name": "MyIconLibrary", "description": "A custom icon library for my personal use.", "icons": []}
        for filename in os.listdir(folder_path):
            if filename.endswith((".png", ".svg", ".jpg", ".gif")):
                icon_name = os.path.splitext(filename)[0]
                icon_url = f"{base_url}{filename}"
                data["icons"].append({"name": icon_name, "url": icon_url})
        with open("icons.json", "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4, ensure_ascii=False)
        EOF

    - name: Commit and Push JSON file
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add icons.json
        git commit -m "Auto-generate icons.json"
        git push
